import {defineField, defineType} from 'sanity'

export const contactPage = defineType({
  name: 'contactPage',
  title: 'Contatti',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Apertura pagina', default: true},
    {name: 'content', title: 'Testi e form'},
    {name: 'map', title: 'Mappa'},
    {name: 'cta', title: 'CTA finale'},
    {name: 'seo', title: 'SEO Google'},
  ],
  fields: [
    defineField({name: 'heroEyebrow', title: 'Etichetta', type: 'string', group: 'hero'}),
    defineField({name: 'heroTitle', title: 'Titolo', type: 'string', group: 'hero', validation: (rule) => rule.required()}),
    defineField({name: 'heroText', title: 'Testo introduttivo', type: 'text', rows: 3, group: 'hero'}),
    defineField({
      name: 'heroImage',
      title: 'Immagine hero opzionale',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({name: 'locationTitle', title: 'Titolo Dove siamo', type: 'string', group: 'content'}),
    defineField({name: 'hoursTitle', title: 'Titolo Orari', type: 'string', group: 'content'}),
    defineField({name: 'hoursIntro', title: 'Introduzione orari', type: 'string', group: 'content'}),
    defineField({name: 'contactTitle', title: 'Titolo Contattaci', type: 'string', group: 'content'}),
    defineField({name: 'formTitle', title: 'Titolo form', type: 'string', group: 'content'}),
    defineField({name: 'formText', title: 'Testo form', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'nameLabel', title: 'Campo nome - etichetta', type: 'string', group: 'content'}),
    defineField({name: 'namePlaceholder', title: 'Campo nome - suggerimento', type: 'string', group: 'content'}),
    defineField({name: 'emailLabel', title: 'Campo email - etichetta', type: 'string', group: 'content'}),
    defineField({name: 'emailPlaceholder', title: 'Campo email - suggerimento', type: 'string', group: 'content'}),
    defineField({name: 'messageLabel', title: 'Campo messaggio - etichetta', type: 'string', group: 'content'}),
    defineField({name: 'messagePlaceholder', title: 'Campo messaggio - suggerimento', type: 'string', group: 'content'}),
    defineField({name: 'submitLabel', title: 'Bottone form', type: 'string', group: 'content'}),
    defineField({name: 'addressTitle', title: 'Titolo box indirizzo', type: 'string', group: 'content'}),
    defineField({name: 'contactsTitle', title: 'Titolo box contatti', type: 'string', group: 'content'}),
    defineField({name: 'mapLabel', title: 'Titolo accessibile della mappa', description: 'Esempio: Sede La Speziale, Milano.', type: 'string', group: 'map'}),
    defineField({
      name: 'mapQuery',
      title: 'Posizione da mostrare sulla mappa',
      description: "Inserisci l'indirizzo completo o il nome preciso del luogo. Se vuoto viene usato l'indirizzo delle Impostazioni sito.",
      type: 'string',
      group: 'map',
    }),
    defineField({
      name: 'mapUrl',
      title: 'Link della posizione su Google Maps',
      description: 'Link aperto dal pulsante sotto la mappa. Se vuoto viene creato automaticamente dalla posizione indicata sopra.',
      type: 'url',
      group: 'map',
      validation: (rule) => rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'mapImage',
      title: 'Immagine mappa opzionale',
      type: 'image',
      group: 'map',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({name: 'cta', title: 'Contenuto CTA', type: 'pageCta', group: 'cta'}),
    defineField({name: 'seo', title: 'Titolo e descrizione Google', type: 'seo', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Contatti', subtitle: 'Pagina contatti'})},
})
