import {defineArrayMember, defineField, defineType} from 'sanity'

export const homepage = defineType({
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  initialValue: {
    heroTitle: 'Il Metodo La Speziale',
    heroSubtitle:
      'Nutrizione personalizzata, consiglio fitoterapico e supporto al cambiamento in un unico programma costruito intorno a te.',
    heroCtaLabel: 'Scopri il percorso',
    heroCtaLink: '/programmi',
    introEyebrow: 'Perché un approccio diverso',
    introTitle: 'La nutrizione cambia quando cambia il corpo.',
    introLead:
      'Nel corso degli anni abbiamo incontrato molte persone che, di fronte ai cambiamenti del proprio corpo, cercavano risposte diverse dai tradizionali schemi alimentari.',
    introBody:
      'Peso piu difficile da gestire, metabolismo che rallenta, variazioni ormonali, gonfiore e perdita di energia richiedono una valutazione piu ampia e competenze che lavorano insieme. Da questa esperienza nasce il Metodo La Speziale. Lavorare con tre professionisti non significa ricevere piu indicazioni o maggiore confusione: al contrario, la nostra sinergia costruisce un unico percorso, semplice da seguire e facilmente integrabile nella vita di tutti i giorni.',
    value1Title: 'La Dieta',
    value1Text: 'Un piano alimentare su misura, realistico e monitorabile, pensato per entrare nella quotidianita senza restrizioni insostenibili.',
    value2Title: 'La Fitoterapia',
    value2Text: 'Uso mirato di piante officinali e nutraceutici di alto livello per sostenere metabolismo, drenaggio ed equilibrio ormonale.',
    value3Title: 'Il Coaching',
    value3Text: 'Sostegno motivazionale e consapevolezza corporea per rendere il cambiamento piu stabile nel lungo termine.',
    methodEyebrow: 'Un percorso, tre competenze',
    methodTitle: 'Un metodo che semplifica, non complica.',
    methodText:
      'Non ricevi indicazioni separate da professionisti diversi. Ricevi un unico percorso, costruito intorno a te e sostenuto da competenze che lavorano insieme.',
    methodCoreEyebrow: 'Lavorare insieme fa la differenza',
    methodCoreText: 'Tre professionalita, un unico metodo snello.',
    methodCoreLinkLabel: 'Scopri il metodo',
    methodDietLabel: 'Percorsi dedicati',
    methodDietTitle: 'Come possiamo aiutarti',
    methodDietText: 'Ogni persona ha esigenze diverse. Per questo abbiamo sviluppato percorsi dedicati ai principali bisogni che incontriamo ogni giorno nel nostro studio.',
    methodDietItems: ['Gestione peso e ricomposizione', 'Menopausa, anti-age e sport', 'Piano, monitoraggio e adattamenti'],
    methodPhytoLabel: 'Consulenze autonome',
    methodPhytoTitle: 'Le stesse competenze, anche in percorsi dedicati.',
    methodPhytoText: 'La Farmacista Fitoterapeuta e il Tutor del Benessere fanno parte del Metodo La Speziale, ma possono accompagnarti anche attraverso percorsi autonomi, quando rispondono meglio alle tue esigenze.',
    methodPhytoItems: ['Fitoterapia mirata', 'Coaching e consapevolezza', 'Supporto pratico senza piano alimentare'],
    methodPhytoLinkLabel: 'Vai alla fitoterapia',
  },
  groups: [
    {name: 'hero', title: 'Hero iniziale', default: true},
    {name: 'content', title: 'Sezioni pagina'},
    {name: 'method', title: 'Metodo e percorsi'},
    {name: 'seo', title: 'SEO Google'},
  ],
  fields: [
    defineField({
      name: 'heroTitle',
      title: 'Titolo principale',
      description: 'La frase grande che si vede appena si apre il sito.',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Testo sotto al titolo',
      description: 'Due o tre righe per spiegare cosa fa La Speziale.',
      type: 'text',
      rows: 3,
      group: 'hero',
      validation: (rule) => rule.max(220).warning('Meglio restare sotto i 220 caratteri.'),
    }),
    defineField({
      name: 'heroImage',
      title: 'Immagine di sfondo hero',
      description: 'Immagine grande di apertura. Usa una foto orizzontale e pulita.',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
    }),
    defineField({name: 'heroCtaLabel', title: 'Testo bottone principale', type: 'string', group: 'hero'}),
    defineField({
      name: 'heroCtaLink',
      title: 'Link bottone principale',
      description: 'Esempio: /contatti oppure /programmi',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'introEyebrow',
      title: 'Etichetta sezione studio',
      description: 'Piccola introduzione sopra al titolo, per esempio "Lo studio".',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'introTitle',
      title: 'Titolo sezione studio',
      description: 'La frase principale che racconta chi siete e cosa fate.',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(120).warning('Meglio restare sotto i 120 caratteri.'),
    }),
    defineField({
      name: 'introLead',
      title: 'Primo paragrafo',
      type: 'text',
      rows: 4,
      group: 'content',
    }),
    defineField({
      name: 'introBody',
      title: 'Secondo paragrafo',
      type: 'text',
      rows: 5,
      group: 'content',
    }),
    defineField({
      name: 'introText',
      title: 'Vecchio testo introduttivo',
      type: 'text',
      readOnly: true,
      hidden: ({value}) => value === undefined,
      deprecated: {
        reason: 'Contenuto storico conservato. Usa i campi della nuova sezione studio.',
      },
    }),
    defineField({
      name: 'approachImage',
      title: 'Immagine sezione introduttiva',
      type: 'image',
      group: 'content',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({name: 'value1Title', title: 'Valore 1 - Titolo', type: 'string', group: 'content'}),
    defineField({name: 'value1Text', title: 'Valore 1 - Testo', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'value2Title', title: 'Valore 2 - Titolo', type: 'string', group: 'content'}),
    defineField({name: 'value2Text', title: 'Valore 2 - Testo', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'value3Title', title: 'Valore 3 - Titolo', type: 'string', group: 'content'}),
    defineField({name: 'value3Text', title: 'Valore 3 - Testo', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'methodEyebrow', title: 'Etichetta sezione', type: 'string', group: 'method'}),
    defineField({
      name: 'methodTitle',
      title: 'Titolo sezione',
      description: 'Spiega il rapporto tra nutrizione integrata, dieta, fitoterapia e prodotti consigliati.',
      type: 'string',
      group: 'method',
      validation: (rule) => rule.max(130).warning('Meglio restare sotto i 130 caratteri.'),
    }),
    defineField({name: 'methodText', title: 'Testo introduttivo', type: 'text', rows: 4, group: 'method'}),
    defineField({name: 'methodCoreEyebrow', title: 'Etichetta riquadro principale', type: 'string', group: 'method'}),
    defineField({name: 'methodCoreText', title: 'Testo riquadro metodo principale', type: 'text', rows: 4, group: 'method'}),
    defineField({name: 'methodCoreLinkLabel', title: 'Testo link riquadro principale', type: 'string', group: 'method'}),
    defineField({name: 'methodDietLabel', title: 'Etichetta percorso con dieta', type: 'string', group: 'method'}),
    defineField({name: 'methodDietTitle', title: 'Titolo percorso con dieta', type: 'string', group: 'method'}),
    defineField({name: 'methodDietText', title: 'Testo percorso con dieta', type: 'text', rows: 3, group: 'method'}),
    defineField({
      name: 'methodDietItems',
      title: 'Punti percorso con dieta',
      type: 'array',
      group: 'method',
      of: [defineArrayMember({type: 'string'})],
      validation: (rule) => rule.max(4).warning('Meglio non superare 4 punti.'),
    }),
    defineField({name: 'methodPhytoLabel', title: 'Etichetta percorso senza dieta', type: 'string', group: 'method'}),
    defineField({name: 'methodPhytoTitle', title: 'Titolo percorso senza dieta', type: 'string', group: 'method'}),
    defineField({name: 'methodPhytoText', title: 'Testo percorso senza dieta', type: 'text', rows: 3, group: 'method'}),
    defineField({
      name: 'methodPhytoImage',
      title: 'Immagine Consiglio Fitoterapico',
      type: 'image',
      group: 'method',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({
      name: 'methodCoachingImage',
      title: 'Immagine Consulenza di Consapevolezza',
      type: 'image',
      group: 'method',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({
      name: 'methodPhytoItems',
      title: 'Punti percorso senza dieta',
      type: 'array',
      group: 'method',
      of: [defineArrayMember({type: 'string'})],
      validation: (rule) => rule.max(4).warning('Meglio non superare 4 punti.'),
    }),
    defineField({name: 'methodPhytoLinkLabel', title: 'Testo link fitoterapia', type: 'string', group: 'method'}),
    defineField({
      name: 'featuredPrograms',
      title: 'Programmi in evidenza',
      description: 'Scegli i percorsi da mostrare in homepage.',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'program'}]})],
      validation: (rule) => rule.max(3).warning('La homepage mostra al massimo 3 programmi.'),
    }),
    defineField({name: 'finalCta', title: 'CTA finale', type: 'pageCta', group: 'content'}),
    defineField({
      name: 'blocks',
      title: 'Vecchie sezioni componibili',
      type: 'pageBuilder',
      readOnly: true,
      hidden: true,
      deprecated: {
        reason: 'Contenuto storico conservato per compatibilita. Il layout della Homepage ora e protetto.',
      },
    }),
    defineField({name: 'seo', title: 'Titolo e descrizione Google', type: 'seo', group: 'seo'}),
  ],
  preview: {
    select: {title: 'heroTitle', media: 'heroImage'},
    prepare: ({title, media}) => ({title: 'Homepage', subtitle: title, media}),
  },
})
