import {defineArrayMember, defineField, defineType} from 'sanity'

export const product = defineType({
  name: 'product',
  title: 'Prodotti',
  type: 'document',
  orderings: [
    {title: 'Ordine nella pagina', name: 'pageOrder', by: [{field: 'order', direction: 'asc'}, {field: 'title', direction: 'asc'}]},
    {title: 'Nome A-Z', name: 'titleAsc', by: [{field: 'title', direction: 'asc'}]},
  ],
  groups: [
    {name: 'card', title: 'Card prodotto', default: true},
    {name: 'detail', title: 'Pagina dettaglio'},
    {name: 'therapies', title: 'Fitoterapie collegate'},
    {name: 'visibility', title: 'Pubblicazione'},
    {name: 'seo', title: 'SEO Google'},
  ],
  fields: [
    defineField({name: 'title', title: 'Nome prodotto', type: 'string', group: 'card', validation: (rule) => rule.required()}),
    defineField({
      name: 'slug',
      title: 'Indirizzo pagina',
      type: 'slug',
      group: 'card',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'relatedTherapies',
      title: 'Fitoterapie collegate',
      description: 'Se aggiungi una terapia, nella pagina prodotto comparira il pulsante Vai alla terapia. I prodotti si potranno filtrare anche per terapia.',
      type: 'array',
      group: 'therapies',
      of: [defineArrayMember({type: 'reference', to: [{type: 'therapy'}]})],
    }),
    defineField({name: 'category', title: 'Categoria', type: 'string', group: 'card'}),
    defineField({name: 'excerpt', title: 'Descrizione breve della card', type: 'text', rows: 3, group: 'card', validation: (rule) => rule.max(220).warning('Meglio restare sotto i 220 caratteri.')}),
    defineField({name: 'price', title: 'Prezzo o indicazione commerciale', description: 'Esempio: 24,00 euro oppure Disponibile in studio.', type: 'string', group: 'card'}),
    defineField({
      name: 'purchaseUrl',
      title: 'Link acquisto esterno',
      description: 'Indirizzo completo della pagina di acquisto, incluso https://. Se vuoto, il pulsante Acquista non viene mostrato.',
      type: 'url',
      group: 'card',
      validation: (rule) => rule.uri({scheme: ['http', 'https']}).error('Inserisci un indirizzo completo che inizi con http:// o https://.'),
    }),
    defineField({
      name: 'purchaseLabel',
      title: 'Testo pulsante acquisto',
      description: 'Esempio: Acquista oppure Vai allo shop.',
      type: 'string',
      group: 'card',
      initialValue: 'Acquista',
      validation: (rule) => rule.max(40).warning('Meglio usare un testo breve, entro 40 caratteri.'),
    }),
    defineField({
      name: 'coverImage',
      title: 'Immagine prodotto',
      type: 'image',
      group: 'card',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({name: 'tags', title: 'Parole chiave', description: 'Utilizzate anche dalla ricerca prodotti.', type: 'array', group: 'card', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'descriptionTitle', title: 'Titolo descrizione', type: 'string', group: 'detail', initialValue: 'Descrizione'}),
    defineField({name: 'description', title: 'Descrizione completa', type: 'richText', group: 'detail'}),
    defineField({name: 'featuresTitle', title: 'Titolo caratteristiche', type: 'string', group: 'detail', initialValue: 'Caratteristiche'}),
    defineField({name: 'features', title: 'Caratteristiche', type: 'array', group: 'detail', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'ctaLabel', title: 'Testo bottone', type: 'string', group: 'detail'}),
    defineField({name: 'ctaLink', title: 'Link bottone', description: 'Se vuoto porta alla pagina Contatti.', type: 'string', group: 'detail'}),
    defineField({name: 'isPublished', title: 'Pubblicato sul sito', type: 'boolean', group: 'visibility', initialValue: true}),
    defineField({name: 'order', title: 'Ordine nella griglia', type: 'number', group: 'visibility', initialValue: 0}),
    defineField({name: 'seo', title: 'Titolo e descrizione Google', type: 'seo', group: 'seo'}),
  ],
  preview: {
    select: {title: 'title', subtitle: 'category', media: 'coverImage', isPublished: 'isPublished'},
    prepare: ({title, subtitle, media, isPublished}) => ({
      title: title || 'Prodotto senza titolo',
      subtitle: `${isPublished === false ? 'Non pubblicato' : 'Pubblicato'}${subtitle ? ` - ${subtitle}` : ''}`,
      media,
    }),
  },
})
