import {defineArrayMember, defineField, defineType} from 'sanity'

export const program = defineType({
  name: 'program',
  title: 'Programmi',
  type: 'document',
  orderings: [
    {title: 'Ordine nel menu', name: 'menuOrder', by: [{field: 'order', direction: 'asc'}, {field: 'title', direction: 'asc'}]},
    {title: 'Nome A-Z', name: 'titleAsc', by: [{field: 'title', direction: 'asc'}]},
  ],
  groups: [
    {name: 'content', title: 'Contenuto programma', default: true},
    {name: 'sections', title: 'Sezioni visibili'},
    {name: 'overview', title: 'Panoramica'},
    {name: 'benefits', title: 'Benefici'},
    {name: 'process', title: 'Come funziona'},
    {name: 'faqs', title: 'FAQ'},
    {name: 'finalCta', title: 'CTA finale'},
    {name: 'visibility', title: 'Pubblicazione e menu'},
    {name: 'seo', title: 'SEO Google'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Nome del programma',
      description: 'Esempio: Nutrizione Integrata, Menopausa e Premenopausa.',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Indirizzo pagina',
      description: 'Parte finale dell URL. Esempio: nutrizione-integrata genera /programmi/nutrizione-integrata/',
      type: 'slug',
      group: 'content',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Descrizione breve',
      description: 'Testo introduttivo visibile nelle card e sotto al titolo.',
      type: 'text',
      rows: 3,
      group: 'content',
      validation: (rule) => rule.max(220).warning('Meglio restare sotto i 220 caratteri.'),
    }),
    defineField({
      name: 'coverImage',
      title: 'Immagine del programma',
      description: 'Usata sia come immagine card sia come sfondo hero della pagina programma.',
      type: 'image',
      group: 'content',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({name: 'category', title: 'Etichetta sopra il titolo', description: 'Esempio: Percorso personalizzato.', type: 'string', group: 'content'}),
    defineField({name: 'ctaLabel', title: 'Testo bottone consulenza nella hero', type: 'string', group: 'content'}),
    defineField({name: 'ctaLink', title: 'Link bottone consulenza', description: 'Esempio: /contatti', type: 'string', group: 'content'}),
    defineField({name: 'heroPrimaryLabel', title: 'Testo bottone Scopri nella hero', type: 'string', group: 'content'}),
    defineField({
      name: 'showAnchorNav',
      title: 'Mostra menu di ancoraggio sotto la hero',
      type: 'boolean',
      group: 'sections',
      initialValue: true,
    }),
    defineField({name: 'showOverview', title: 'Mostra Panoramica', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showAudience', title: 'Mostra A chi si rivolge', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showDescription', title: 'Mostra Descrizione del percorso', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showBenefits', title: 'Mostra Benefici', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showProcess', title: 'Mostra Come funziona', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showFaqs', title: 'Mostra FAQ', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showExtraContent', title: 'Mostra sezioni editoriali extra', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showFinalCta', title: 'Mostra CTA finale', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'duration', title: 'Durata', description: 'Esempio: Percorso personalizzato.', type: 'string', group: 'overview', hidden: ({document}) => document?.showOverview === false}),
    defineField({name: 'programType', title: 'Tipologia', description: 'Esempio: Percorso su consulenza.', type: 'string', group: 'overview', hidden: ({document}) => document?.showOverview === false}),
    defineField({name: 'deliveryMode', title: 'Modalita', description: 'Esempio: Online o in studio.', type: 'string', group: 'overview', hidden: ({document}) => document?.showOverview === false}),
    defineField({name: 'personalizedNote', title: 'Nota personalizzazione', description: 'Esempio: Piano su misura in base alle tue esigenze.', type: 'text', rows: 2, group: 'overview', hidden: ({document}) => document?.showOverview === false}),
    defineField({name: 'price', title: 'Prezzo opzionale', type: 'string', group: 'overview', hidden: ({document}) => document?.showOverview === false}),
    defineField({name: 'isPublished', title: 'Pubblicato', type: 'boolean', group: 'visibility', initialValue: true}),
    defineField({name: 'showInMenu', title: 'Visibile nel menu', type: 'boolean', group: 'visibility', initialValue: true}),
    defineField({name: 'isFeatured', title: 'In evidenza', type: 'boolean', group: 'visibility', initialValue: false}),
    defineField({name: 'order', title: 'Ordine', type: 'number', group: 'visibility', initialValue: 0}),
    defineField({
      name: 'audience',
      title: 'Destinatari',
      type: 'array',
      group: 'overview',
      hidden: ({document}) => document?.showAudience === false,
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({name: 'descriptionTitle', title: 'Titolo descrizione', type: 'string', group: 'overview', initialValue: 'Il percorso', hidden: ({document}) => document?.showDescription === false}),
    defineField({name: 'audienceTitle', title: 'Titolo sezione destinatari', type: 'string', group: 'overview', initialValue: 'A chi si rivolge', hidden: ({document}) => document?.showAudience === false}),
    defineField({
      name: 'description',
      title: 'Descrizione del percorso',
      description: 'Testo principale mostrato nella panoramica.',
      type: 'richText',
      group: 'overview',
      hidden: ({document}) => document?.showDescription === false,
    }),
    defineField({
      name: 'benefits',
      title: 'Benefici semplici precedenti',
      description: 'Campo mantenuto solo per compatibilita con i contenuti esistenti.',
      type: 'array',
      group: 'benefits',
      hidden: true,
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({
      name: 'benefitCards',
      title: 'Benefici del percorso',
      description: 'Aggiungi icona, titolo e descrizione per ogni beneficio.',
      type: 'array',
      group: 'benefits',
      hidden: ({document}) => document?.showBenefits === false,
      of: [defineArrayMember({type: 'programBenefit'})],
    }),
    defineField({name: 'benefitsTitle', title: 'Titolo sezione benefici', type: 'string', group: 'benefits', initialValue: 'I benefici del percorso', hidden: ({document}) => document?.showBenefits === false}),
    defineField({
      name: 'processSteps',
      title: 'Passaggi del percorso',
      type: 'array',
      group: 'process',
      hidden: ({document}) => document?.showProcess === false,
      of: [defineArrayMember({type: 'programStep'})],
      validation: (rule) => rule.max(5).warning('Per una timeline chiara usa al massimo 5 passaggi.'),
    }),
    defineField({name: 'processTitle', title: 'Titolo sezione', type: 'string', group: 'process', initialValue: 'Come funziona il percorso', hidden: ({document}) => document?.showProcess === false}),
    defineField({
      name: 'faqs',
      title: 'FAQ specifiche',
      type: 'array',
      group: 'faqs',
      hidden: ({document}) => document?.showFaqs === false,
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'question', title: 'Domanda', type: 'string'}),
            defineField({name: 'answer', title: 'Risposta', type: 'text', rows: 4}),
          ],
          preview: {select: {title: 'question', subtitle: 'answer'}},
        }),
      ],
    }),
    defineField({name: 'faqsTitle', title: 'Titolo sezione FAQ', type: 'string', group: 'faqs', initialValue: 'Domande frequenti', hidden: ({document}) => document?.showFaqs === false}),
    defineField({name: 'finalCtaTitle', title: 'Titolo CTA finale', type: 'string', group: 'finalCta', hidden: ({document}) => document?.showFinalCta === false}),
    defineField({name: 'finalCtaText', title: 'Testo CTA finale', type: 'text', rows: 3, group: 'finalCta', hidden: ({document}) => document?.showFinalCta === false}),
    defineField({name: 'finalWhatsappLabel', title: 'Testo bottone WhatsApp', type: 'string', group: 'finalCta', hidden: ({document}) => document?.showFinalCta === false}),
    defineField({name: 'finalEmailLabel', title: 'Testo bottone email', type: 'string', group: 'finalCta', hidden: ({document}) => document?.showFinalCta === false}),
    defineField({
      name: 'finalCtaImage',
      title: 'Immagine CTA finale',
      type: 'image',
      group: 'finalCta',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
      hidden: ({document}) => document?.showFinalCta === false,
    }),
    defineField({name: 'blocks', title: 'Sezioni editoriali extra', description: 'Opzionale: contenuti aggiuntivi dopo la panoramica.', type: 'pageBuilder', group: 'overview', hidden: ({document}) => document?.showExtraContent === false}),
    defineField({name: 'seo', title: 'Titolo e descrizione Google', type: 'seo', group: 'seo'}),
  ],
  preview: {
    select: {title: 'title', subtitle: 'category', media: 'coverImage', isPublished: 'isPublished'},
    prepare: ({title, subtitle, media, isPublished}) => ({
      title: title || 'Programma senza titolo',
      subtitle: `${isPublished === false ? 'Bozza' : 'Pubblicato'}${subtitle ? ` - ${subtitle}` : ''}`,
      media,
    }),
  },
})
