import {defineArrayMember, defineField, defineType} from 'sanity'

export const testimonialsPage = defineType({
  name: 'testimonialsPage',
  title: 'Dicono di noi',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Apertura pagina', default: true},
    {name: 'content', title: 'Testimonianze'},
    {name: 'google', title: 'Recensioni Google'},
    {name: 'cta', title: 'CTA finale'},
    {name: 'seo', title: 'SEO Google'},
  ],
  fields: [
    defineField({name: 'heroEyebrow', title: 'Etichetta', type: 'string', group: 'hero'}),
    defineField({name: 'heroTitle', title: 'Titolo', type: 'string', group: 'hero', validation: (rule) => rule.required()}),
    defineField({name: 'heroText', title: 'Testo introduttivo', type: 'text', rows: 3, group: 'hero'}),
    defineField({
      name: 'heroImage',
      title: 'Immagine hero opzionale',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({name: 'sectionTitle', title: 'Titolo sopra le testimonianze', type: 'string', group: 'content'}),
    defineField({name: 'sectionText', title: 'Testo sopra le testimonianze', type: 'text', rows: 4, group: 'content'}),
    defineField({
      name: 'showGoogleReviews',
      title: 'Mostra recensioni Google',
      description: 'Attiva o nasconde l intera sezione sul sito.',
      type: 'boolean',
      group: 'google',
      initialValue: false,
    }),
    defineField({name: 'googleEyebrow', title: 'Etichetta sezione', type: 'string', group: 'google', hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({name: 'googleTitle', title: 'Titolo sezione', type: 'string', group: 'google', hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({name: 'googleText', title: 'Testo introduttivo', type: 'text', rows: 3, group: 'google', hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({name: 'googleBusinessName', title: 'Nome attivita su Google', type: 'string', group: 'google', hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({name: 'googleRating', title: 'Valutazione media', description: 'Esempio: 4.9', type: 'number', group: 'google', validation: (rule) => rule.min(0).max(5), hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({name: 'googleReviewCount', title: 'Numero totale recensioni', type: 'number', group: 'google', validation: (rule) => rule.integer().min(0), hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({name: 'googleReviewsUrl', title: 'Link scheda o recensioni Google', type: 'url', group: 'google', validation: (rule) => rule.uri({scheme: ['http', 'https']}), hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({name: 'googlePlaceId', title: 'Google Place ID opzionale', description: 'Conservalo qui per una futura sincronizzazione automatica tramite Google Places API.', type: 'string', group: 'google', hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({
      name: 'googleReviews',
      title: 'Recensioni da mostrare',
      description: 'Seleziona e riporta solo recensioni pubbliche pertinenti presenti nella scheda Google.',
      type: 'array',
      group: 'google',
      of: [defineArrayMember({type: 'googleReview'})],
      validation: (rule) => rule.max(6).warning('Per una pagina leggibile mostra al massimo 6 recensioni.'),
      hidden: ({document}) => document?.showGoogleReviews !== true,
    }),
    defineField({name: 'googleButtonLabel', title: 'Testo bottone Google', type: 'string', group: 'google', hidden: ({document}) => document?.showGoogleReviews !== true}),
    defineField({name: 'cta', title: 'Contenuto CTA', type: 'pageCta', group: 'cta'}),
    defineField({name: 'seo', title: 'Titolo e descrizione Google', type: 'seo', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Dicono di noi', subtitle: 'Pagina testimonianze'})},
})
