import {defineArrayMember, defineField, defineType} from 'sanity'

export const therapy = defineType({
  name: 'therapy',
  title: 'Fitoterapie',
  type: 'document',
  orderings: [
    {title: 'Ordine nella pagina', name: 'pageOrder', by: [{field: 'order', direction: 'asc'}, {field: 'title', direction: 'asc'}]},
    {title: 'Nome A-Z', name: 'titleAsc', by: [{field: 'title', direction: 'asc'}]},
  ],
  groups: [
    {name: 'content', title: 'Contenuto terapia', default: true},
    {name: 'sections', title: 'Sezioni visibili'},
    {name: 'overview', title: 'Panoramica'},
    {name: 'benefits', title: 'Benefici'},
    {name: 'products', title: 'Prodotti consigliati'},
    {name: 'faqs', title: 'FAQ'},
    {name: 'finalCta', title: 'CTA finale'},
    {name: 'visibility', title: 'Pubblicazione e menu'},
    {name: 'seo', title: 'SEO Google'},
  ],
  fields: [
    defineField({name: 'title', title: 'Nome terapia', type: 'string', group: 'content', validation: (rule) => rule.required()}),
    defineField({
      name: 'slug',
      title: 'Indirizzo pagina',
      description: 'Parte finale dell URL. Esempio: vascolarizzazione-gambe genera /fitoterapia/vascolarizzazione-gambe/',
      type: 'slug',
      group: 'content',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'excerpt', title: 'Descrizione breve', type: 'text', rows: 3, group: 'content', validation: (rule) => rule.max(230).warning('Meglio restare sotto i 230 caratteri.')}),
    defineField({
      name: 'tagLabel',
      title: 'Etichetta breve per i filtri',
      description: 'Una parola breve mostrata nei bottoni rapidi della pagina Fitoterapia. Esempio: Capelli, Peso, Sonno.',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(24).warning('Meglio usare una parola breve.'),
    }),
    defineField({
      name: 'gridTitle',
      title: 'Domanda mostrata nella pagina Fitoterapia',
      description: 'Titolo della card nella pagina generale. Puoi usare una domanda, per esempio: "Noti capelli piu deboli?".',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(130).warning('Meglio restare sotto i 130 caratteri.'),
    }),
    defineField({
      name: 'gridButtonLabel',
      title: 'Testo bottone nella pagina Fitoterapia',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'coverImage',
      title: 'Immagine terapia',
      type: 'image',
      group: 'content',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})],
    }),
    defineField({name: 'category', title: 'Etichetta sopra il titolo', type: 'string', group: 'content', initialValue: 'Consiglio fitoterapico'}),
    defineField({name: 'ctaLabel', title: 'Testo bottone consulenza nella hero', type: 'string', group: 'content', initialValue: 'Prenota una consulenza'}),
    defineField({name: 'ctaLink', title: 'Link bottone consulenza', type: 'string', group: 'content', initialValue: '/contatti'}),
    defineField({name: 'heroPrimaryLabel', title: 'Testo bottone Scopri nella hero', type: 'string', group: 'content', initialValue: 'Scopri i consigli'}),
    defineField({name: 'showAnchorNav', title: 'Mostra menu di ancoraggio', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showOverview', title: 'Mostra Panoramica', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showBenefits', title: 'Mostra Benefici', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showRecommendedProducts', title: 'Mostra Prodotti consigliati', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showFaqs', title: 'Mostra FAQ', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'showFinalCta', title: 'Mostra CTA finale', type: 'boolean', group: 'sections', initialValue: true}),
    defineField({name: 'overviewTitle', title: 'Titolo panoramica', type: 'string', group: 'overview', initialValue: 'Quando puo essere utile', hidden: ({document}) => document?.showOverview === false}),
    defineField({name: 'description', title: 'Descrizione completa', type: 'richText', group: 'overview', hidden: ({document}) => document?.showOverview === false}),
    defineField({name: 'notesTitle', title: 'Titolo note', type: 'string', group: 'overview', initialValue: 'Indicazioni importanti', hidden: ({document}) => document?.showOverview === false}),
    defineField({name: 'notes', title: 'Note importanti', type: 'array', group: 'overview', hidden: ({document}) => document?.showOverview === false, of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'benefitsTitle', title: 'Titolo benefici', type: 'string', group: 'benefits', initialValue: 'I benefici del supporto', hidden: ({document}) => document?.showBenefits === false}),
    defineField({name: 'benefitCards', title: 'Benefici', type: 'array', group: 'benefits', hidden: ({document}) => document?.showBenefits === false, of: [defineArrayMember({type: 'programBenefit'})]}),
    defineField({
      name: 'recommendedProducts',
      title: 'Prodotti consigliati',
      description: 'I prodotti scelti qui appariranno nella pagina della terapia. Il collegamento funziona anche al contrario dalla scheda prodotto.',
      type: 'array',
      group: 'products',
      hidden: ({document}) => document?.showRecommendedProducts === false,
      of: [defineArrayMember({type: 'reference', to: [{type: 'product'}]})],
    }),
    defineField({name: 'recommendedProductsTitle', title: 'Titolo prodotti consigliati', type: 'string', group: 'products', initialValue: 'Prodotti consigliati', hidden: ({document}) => document?.showRecommendedProducts === false}),
    defineField({
      name: 'faqs',
      title: 'FAQ terapia',
      type: 'array',
      group: 'faqs',
      hidden: ({document}) => document?.showFaqs === false,
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'question', title: 'Domanda', type: 'string'}),
            defineField({name: 'answer', title: 'Risposta', type: 'text', rows: 4}),
          ],
          preview: {select: {title: 'question', subtitle: 'answer'}},
        }),
      ],
    }),
    defineField({name: 'faqsTitle', title: 'Titolo FAQ', type: 'string', group: 'faqs', initialValue: 'Domande frequenti', hidden: ({document}) => document?.showFaqs === false}),
    defineField({name: 'finalCtaTitle', title: 'Titolo CTA finale', type: 'string', group: 'finalCta', hidden: ({document}) => document?.showFinalCta === false}),
    defineField({name: 'finalCtaText', title: 'Testo CTA finale', type: 'text', rows: 3, group: 'finalCta', hidden: ({document}) => document?.showFinalCta === false}),
    defineField({name: 'finalCtaImage', title: 'Immagine CTA finale', type: 'image', group: 'finalCta', options: {hotspot: true}, fields: [defineField({name: 'alt', title: 'Testo alternativo', type: 'string'})], hidden: ({document}) => document?.showFinalCta === false}),
    defineField({name: 'isPublished', title: 'Pubblicata sul sito', type: 'boolean', group: 'visibility', initialValue: true}),
    defineField({
      name: 'showInMenu',
      title: 'Visibile nel menu',
      type: 'boolean',
      group: 'visibility',
      initialValue: false,
      readOnly: true,
      deprecated: {reason: 'Le fitoterapie non vengono piu elencate nella navbar principale.'},
    }),
    defineField({name: 'order', title: 'Ordine', type: 'number', group: 'visibility', initialValue: 0}),
    defineField({name: 'seo', title: 'Titolo e descrizione Google', type: 'seo', group: 'seo'}),
  ],
  preview: {
    select: {title: 'title', subtitle: 'category', media: 'coverImage', isPublished: 'isPublished'},
    prepare: ({title, subtitle, media, isPublished}) => ({
      title: title || 'Terapia senza titolo',
      subtitle: `${isPublished === false ? 'Bozza' : 'Pubblicata'}${subtitle ? ` - ${subtitle}` : ''}`,
      media,
    }),
  },
})
